# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Filter-Stomp
version:      0.02
version_from: lib/POE/Filter/Stomp.pm
installdirs:  site
requires:
    Net::Stomp:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
